// Code generated by inco. DO NOT EDIT.

package directive

import (
	"go/ast"
	"regexp"
	"strings"
)

var (
	// directiveRe matches the body after stripping comment delimiters.
	// Group 1: prefix (@inco or @if)
	// Group 2: everything after the colon+space
	directiveRe = regexp.MustCompile(`^(@inco|@if):\s+(.+)$`)

	// actionRe splits "expr, -action(args)" into components.
	// Greedy (.+) backtracks to find the last top-level ", -action..." —
	// this naturally handles commas inside parenthesized sub-expressions.
	//
	// Group 1: expression
	// Group 2: action name (panic|return|continue|break)
	// Group 3: action arguments (optional)
	actionRe = regexp.MustCompile(`^(.+),\s*-(panic|return|continue|break|log)(?:\((.+)\))?\s*$`)

	// commentRe strips Go comment delimiters.
	// Group 1: content of // comment
	// Group 2: content of /* */ comment
	commentRe = regexp.MustCompile(`^//\s*(.*?)\s*$|^/\*\s*(.*?)\s*\*/$`)
)

// actionFromName maps action name strings to ActionKind.
var actionFromName = map[string]ActionKind{
	"panic":    ActionPanic,
	"return":   ActionReturn,
	"continue": ActionContinue,
	"break":    ActionBreak,
	"log":      ActionLog,
}

// ParseDirective extracts a Directive from a comment string.
// Returns nil when the comment is not a valid directive.
//
// Recognized prefixes: @inco: (contract) and @if: (guard).
// Full syntax: <prefix>: <expr>[, -action[(args...)]]
func ParseDirective(comment string) *Directive {
	body := stripComment(comment)
//line /home/runner/work/inco/inco/internal/directive/parse.inco.go:46
	if !(body != "") {
		return nil
	}
//line /home/runner/work/inco/inco/internal/directive/parse.inco.go:47

	m := directiveRe.FindStringSubmatch(body)
//line /home/runner/work/inco/inco/internal/directive/parse.inco.go:49
	if !(m != nil) {
		return nil
	}
//line /home/runner/work/inco/inco/internal/directive/parse.inco.go:50

	prefix := m[1]
	rest := m[2]

	d := &Directive{Action: ActionPanic}
	d.Negated = (prefix == "@if")

	if am := actionRe.FindStringSubmatch(rest); am != nil {
		d.Expr = strings.TrimSpace(am[1])
		d.Action = actionFromName[am[2]]
		if am[3] != "" {
			d.ActionArgs = splitTopLevel(am[3])
		}
	} else {
		d.Expr = rest
	}

//line /home/runner/work/inco/inco/internal/directive/parse.inco.go:67
	if !(d.Expr != "") {
		return nil
	}
//line /home/runner/work/inco/inco/internal/directive/parse.inco.go:68

	return d
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// stripComment removes Go comment delimiters and returns trimmed content.
func stripComment(s string) string {
	s = strings.TrimSpace(s)
	m := commentRe.FindStringSubmatch(s)

	// m[1] is // content, m[2] is /* */ content; exactly one is non-empty.
//line /home/runner/work/inco/inco/internal/directive/parse.inco.go:82
	if !(m != nil) {
		return ""
	}
//line /home/runner/work/inco/inco/internal/directive/parse.inco.go:83

	return m[1] + m[2]
}

// splitTopLevel splits s by top-level commas, respecting nested parens,
// brackets, braces, double-quoted strings, and raw strings (backtick).
func splitTopLevel(s string) []string {

	var result []string
	depth := 0
	start := 0
	for i := 0; i < len(s); i++ {
		ch := s[i]
		switch {
		case ch == '"':
			// Double-quoted string: skip until unescaped closing quote.
			i++
			for i < len(s) {
				if s[i] == '\\' {
					i++ // skip escaped char
				} else if s[i] == '"' {
					break
				}
				i++
			}
		case ch == '`':
			// Raw string: no escapes, skip until closing backtick.
			i++
			for i < len(s) && s[i] != '`' {
				i++
			}
		case ch == '(' || ch == '[' || ch == '{':
			depth++
		case ch == ')' || ch == ']' || ch == '}':
			depth--
		case ch == ',' && depth == 0:
			result = append(result, strings.TrimSpace(s[start:i]))
			start = i + 1
		}
	}
	if last := strings.TrimSpace(s[start:]); last != "" {
		result = append(result, last)
	}
	return result
}

// ---------------------------------------------------------------------------
// AST helpers
// ---------------------------------------------------------------------------

// collectDeclCommentGroups returns the set of comment groups that are attached
// to declarations — both doc comments (.Doc) and trailing line comments
// (.Comment). These must be skipped when scanning for directives, because
// they may contain directive-like syntax in documentation or decorative
// comments (e.g. struct field annotations).
func collectDeclCommentGroups(f *ast.File) map[*ast.CommentGroup]bool {
	groups := make(map[*ast.CommentGroup]bool)
	if f.Doc != nil {
		groups[f.Doc] = true
	}
	ast.Inspect(f, func(n ast.Node) bool {
		switch x := n.(type) {
		case *ast.FuncDecl:
			if x.Doc != nil {
				groups[x.Doc] = true
			}
		case *ast.GenDecl:
			if x.Doc != nil {
				groups[x.Doc] = true
			}
		case *ast.TypeSpec:
			if x.Doc != nil {
				groups[x.Doc] = true
			}
			if x.Comment != nil {
				groups[x.Comment] = true
			}
		case *ast.Field:
			if x.Doc != nil {
				groups[x.Doc] = true
			}
			if x.Comment != nil {
				groups[x.Comment] = true
			}
		case *ast.ValueSpec:
			if x.Doc != nil {
				groups[x.Doc] = true
			}
			if x.Comment != nil {
				groups[x.Comment] = true
			}
		}
		return true
	})
	return groups
}

// CollectDirectives iterates over all comments in f, skips doc comment
// groups, parses each as a directive, and calls fn for every valid match.
// This is the shared scanning logic used by both engine and audit.
func CollectDirectives(f *ast.File, fn func(c *ast.Comment, d *Directive)) {
	declGroups := collectDeclCommentGroups(f)
	for _, cg := range f.Comments {
		_ = declGroups // @if: declGroups[cg], -continue
//line /home/runner/work/inco/inco/internal/directive/parse.inco.go:186
		if declGroups[cg] {
			continue
		}
//line /home/runner/work/inco/inco/internal/directive/parse.inco.go:187

		for _, c := range cg.List {
			d := ParseDirective(c.Text)
//line /home/runner/work/inco/inco/internal/directive/parse.inco.go:190
			if d == nil {
				continue
			}
//line /home/runner/work/inco/inco/internal/directive/parse.inco.go:191

			fn(c, d)
		}
	}
}
