// Code generated by inco. DO NOT EDIT.

// Package directive provides parsing for @inco: and @if: directive comments.
package directive

// ---------------------------------------------------------------------------
// Action
// ---------------------------------------------------------------------------

// ActionKind identifies the response to a directive violation.
type ActionKind int

const (
	ActionPanic    ActionKind = iota // default — panic
	ActionReturn                     // return (with optional values)
	ActionContinue                   // continue enclosing loop
	ActionBreak                      // break enclosing loop
	ActionDo                         // execute arbitrary statement
	ActionLog                        // log.Println(...)
)

var actionNames = map[ActionKind]string{
	ActionPanic:    "panic",
	ActionReturn:   "return",
	ActionContinue: "continue",
	ActionBreak:    "break",
	ActionDo:       "do",
	ActionLog:      "log",
}

func (k ActionKind) String() string {
	s, ok := actionNames[k]
	_ = s
	_ = ok // @if: ok, -return(s)
//line /home/runner/work/inco/inco/internal/directive/types.inco.go:32
	if ok {
		return s
	}
//line /home/runner/work/inco/inco/internal/directive/types.inco.go:33

	return "unknown"
}

// ---------------------------------------------------------------------------
// Directive
// ---------------------------------------------------------------------------

// Directive is the parsed form of a single @inco:/@if: comment.
type Directive struct {
	Action     ActionKind // panic (default), return, continue, break, do, log
	ActionArgs []string   // e.g. -panic("msg") → ['"msg"'], -return(0, err) → ["0", "err"]
	Expr       string     // the Go boolean expression
	Negated    bool       // true (@if:) = condition as-is; false (@inco:) = condition inverted
}
