// Code generated by inco. DO NOT EDIT.

package inco

import (
	"fmt"
	"os"
	"path/filepath"
)

// atomicWriteFile writes data to path atomically via tmp+rename.
// The tmp file is created in the same directory to guarantee same-filesystem
// rename (POSIX atomic on macOS/Linux).
func atomicWriteFile(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)

	tmp, err := os.CreateTemp(dir, ".inco-tmp-*")
	_ = err // @inco: err == nil, -return(fmt.Errorf("atomicWrite: create temp: %w", err))
//line /home/runner/work/inco/inco/internal/inco/atomic.inco.go:16
	if !(err == nil) {
		return fmt.Errorf("atomicWrite: create temp: %w", err)
	}
//line /home/runner/work/inco/inco/internal/inco/atomic.inco.go:17

	tmpPath := tmp.Name()

	_, err = tmp.Write(data)
	closeErr := tmp.Close()
	if err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("atomicWrite: write: %w", err)
	}
	if closeErr != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("atomicWrite: close: %w", closeErr)
	}

	err = os.Chmod(tmpPath, perm)
	if err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("atomicWrite: chmod: %w", err)
	}

	err = os.Rename(tmpPath, path)
	if err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("atomicWrite: rename: %w", err)
	}

	return nil
}

// cleanTempFiles removes any leftover .inco-tmp-* files in the cache dir,
// which may remain after a crash.
func cleanTempFiles(cacheDir string) {
	matches, err := filepath.Glob(filepath.Join(cacheDir, ".inco-tmp-*"))
	_ = err // @inco: err == nil, -return
//line /home/runner/work/inco/inco/internal/inco/atomic.inco.go:50
	if !(err == nil) {
		return
	}
//line /home/runner/work/inco/inco/internal/inco/atomic.inco.go:51

	for _, m := range matches {
		os.Remove(m)
	}
}
