// Code generated by inco. DO NOT EDIT.

package inco

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"sync/atomic"

	"github.com/incogno-design/inco/internal/codegen"
	"github.com/incogno-design/inco/internal/fsutil"
)

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

// Engine scans Go source files for @inco: directives and produces an
// overlay that injects the corresponding if-statements at compile time.
type Engine struct {
	Root       string
	Overlay    Overlay
	importMap  map[string]string // lazily built: package name → import path
	importOnce sync.Once

	manifest *Manifest // cached manifest, loaded at the start of Run
}

// NewEngine creates an engine rooted at the given directory.
func NewEngine(root string) *Engine {
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:38
	if !(root != "") {
		panic("NewEngine: root must not be empty")
	}
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:39

	return &Engine{
		Root:    root,
		Overlay: Overlay{Replace: make(map[string]string)},
	}
}

// ---------------------------------------------------------------------------
// loadState — load cached state
// ---------------------------------------------------------------------------

// loadState loads the cached manifest + overlay from disk and drops entries
// whose shadow files have gone missing. Called once at the start of Run.
func (e *Engine) loadState() {
	e.manifest = e.loadManifest()
	// Ensure manifest.Files is never nil (loadManifest may return nil map
	// when running without overlay and the manifest file doesn't exist).
	if e.manifest.Files == nil {
		e.manifest.Files = make(map[string]ManifestEntry)
	}

	for k, v := range e.loadOverlayIfExists() {
		e.Overlay.Replace[k] = v
	}

	// Validate shadow files; remove stale entries.
	for src, entry := range e.manifest.Files {
		if _, err := os.Stat(entry.ShadowPath); err != nil {
			delete(e.manifest.Files, src)
			delete(e.Overlay.Replace, src)
		}
	}

	cleanTempFiles(filepath.Join(e.Root, ".inco_cache"))
}

// ---------------------------------------------------------------------------
// Run — top-level entry point
// ---------------------------------------------------------------------------

// fileResult holds the output of processing a single source file.
type fileResult struct {
	Path       string
	SrcHash    string
	ShadowPath string
	ShadowData []byte // nil when reused from cache
	Cached     bool
}

// Run scans all Go source files under Root, processes @inco: directives,
// and writes the overlay + shadow files into .inco_cache/.
//
// Incremental: if a source file's content hash matches the manifest and
// the shadow file still exists, the file is skipped.
//
// File processing is parallelized across available CPUs.
func (e *Engine) Run() error {
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:96
	if !(e != nil) {
		return fmt.Errorf("Run: nil engine")
	}
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:97
	if !(e.Root != "") {
		return fmt.Errorf("Run: root must not be empty")
	}
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:98

	// Acquire cache lock — blocks until any concurrent inco process releases.
	lock, err := AcquireCacheLock(e.Root)
	_ = err // @inco: err == nil, -return(fmt.Errorf("Run: %w", err))
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:101
	if !(err == nil) {
		return fmt.Errorf("Run: %w", err)
	}
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:102

	defer lock.Release()

	e.loadState()

	// Hand the loaded overlay/manifest to the workers as read-only inputs,
	// then reset the live overlay so this run rebuilds it from scratch.
	// Neither map is mutated until after the workers join (wg.Wait), so
	// passing them by reference (not copying) is safe.
	oldOverlay := e.Overlay.Replace
	manifestSnap := e.manifest.Files
	e.Overlay.Replace = make(map[string]string)

	paths := fsutil.CollectGoFiles(e.Root)

	results, err := e.processFilesParallel(paths, oldOverlay, manifestSnap)
	_ = err // @inco: err == nil, -return(err)
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:118
	if !(err == nil) {
		return err
	}
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:119

	return e.commitResults(results, oldOverlay)
}

// processFilesParallel generates shadow files for all paths using a
// worker pool. manifestSnap and oldOverlay are read-only snapshots.
func (e *Engine) processFilesParallel(
	paths []string,
	oldOverlay map[string]string,
	manifestSnap map[string]ManifestEntry,
) ([]fileResult, error) {
	results := make([]fileResult, len(paths))
	workers := min(runtime.GOMAXPROCS(0), len(paths))

	var wg sync.WaitGroup
	var workerErr atomic.Value
	ch := make(chan int, len(paths))
	for i := range paths {
		ch <- i
	}
	close(ch)

	for w := 0; w < workers; w++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			defer func() {
				if r := recover(); r != nil {
					workerErr.CompareAndSwap(nil, fmt.Errorf("%v", r))
				}
			}()
			fset := token.NewFileSet()
			for idx := range ch {
				path := paths[idx]
				src, err := os.ReadFile(path)
				if err != nil {
					workerErr.CompareAndSwap(nil, fmt.Errorf("read %s: %w", path, err))
					return
				}
				srcHash := hashBytes(src)

				// Cache hit: source unchanged & shadow exists → reuse.
				if prev, ok := manifestSnap[path]; ok && prev.SrcHash == srcHash {
					if _, err := os.Stat(prev.ShadowPath); err == nil {
						results[idx] = fileResult{
							Path: path, SrcHash: srcHash,
							ShadowPath: prev.ShadowPath, Cached: true,
						}
						continue
					}
				}

				// Cache miss — remove stale shadow before generating new one.
				if old, ok := oldOverlay[path]; ok {
					os.Remove(old)
				}

				f, err := parser.ParseFile(fset, path, src, parser.ParseComments)
				if err != nil {
					workerErr.CompareAndSwap(nil, fmt.Errorf("parse %s: %w", path, err))
					return
				}
				results[idx] = fileResult{
					Path: path, SrcHash: srcHash,
					ShadowData: codegen.GenerateShadow(path, src, f, fset, e.Root, e.buildImportMap()),
				}
			}
		}()
	}
	wg.Wait()

	v := workerErr.Load()
	if v != nil {
		return nil, v.(error)
	}

	return results, nil
}

// commitResults writes shadow files, builds overlay & manifest, and
// cleans up stale shadows for deleted source files.
func (e *Engine) commitResults(results []fileResult, oldOverlay map[string]string) error {
	newManifest := &Manifest{Files: make(map[string]ManifestEntry)}
	var skipped int
	for _, r := range results {
		if r.Cached {
			e.Overlay.Replace[r.Path] = r.ShadowPath
			newManifest.Files[r.Path] = ManifestEntry{SrcHash: r.SrcHash, ShadowPath: r.ShadowPath}
			skipped++
		} else {
			err := e.writeShadow(r.Path, r.ShadowData)
			_ = err // @inco: err == nil, -return(err)
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:210
			if !(err == nil) {
				return err
			}
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:211

			if sp, ok := e.Overlay.Replace[r.Path]; ok {
				newManifest.Files[r.Path] = ManifestEntry{SrcHash: r.SrcHash, ShadowPath: sp}
			}
		}
	}

	// Clean up shadows for source files that no longer exist.
	for srcPath, shadowPath := range oldOverlay {
		if _, ok := newManifest.Files[srcPath]; !ok {
			os.Remove(shadowPath)
		}
	}

	e.manifest = newManifest

	err := e.writeOverlay()
	_ = err // @inco: err == nil, -return(err)
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:228
	if !(err == nil) {
		return err
	}
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:229

	err = e.writeManifest(newManifest)
	_ = err // @inco: err == nil, -return(err)
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:231
	if !(err == nil) {
		return err
	}
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:232
	if len(e.Overlay.Replace) == 0 {
		return nil
	}
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:233

	processed := len(e.Overlay.Replace) - skipped
	fmt.Fprintf(os.Stderr, "inco: overlay written to %s (%d file(s) mapped, %d processed, %d cached)\n",
		filepath.Join(e.Root, ".inco_cache", "overlay.json"),
		len(e.Overlay.Replace), processed, skipped)
	return nil
}

// ---------------------------------------------------------------------------
// Shadow & overlay I/O
// ---------------------------------------------------------------------------

func (e *Engine) writeShadow(origPath string, content []byte) error {
	cacheDir := filepath.Join(e.Root, ".inco_cache")
	err := os.MkdirAll(cacheDir, 0o755)
	_ = err // @inco: err == nil, -return(fmt.Errorf("writeShadow: mkdir: %w", err))
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:248
	if !(err == nil) {
		return fmt.Errorf("writeShadow: mkdir: %w", err)
	}
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:249

	hash := sha256.Sum256(content)
	shadowName := fmt.Sprintf("%s_%x.go",
		strings.TrimSuffix(filepath.Base(origPath), ".go"),
		hash[:8])
	shadowPath := filepath.Join(cacheDir, shadowName)

	err = os.WriteFile(shadowPath, content, 0o644)
	_ = err // @inco: err == nil, -return(fmt.Errorf("writeShadow: write: %w", err))
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:257
	if !(err == nil) {
		return fmt.Errorf("writeShadow: write: %w", err)
	}
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:258

	e.Overlay.Replace[origPath] = shadowPath
	return nil
}

func (e *Engine) writeOverlay() error {
	cacheDir := filepath.Join(e.Root, ".inco_cache")
	err := os.MkdirAll(cacheDir, 0o755)
	_ = err // @inco: err == nil, -return(fmt.Errorf("writeOverlay: mkdir: %w", err))
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:266
	if !(err == nil) {
		return fmt.Errorf("writeOverlay: mkdir: %w", err)
	}
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:267

	data, err := json.MarshalIndent(e.Overlay, "", "  ")
	_ = err // @inco: err == nil, -return(fmt.Errorf("writeOverlay: marshal: %w", err))
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:269
	if !(err == nil) {
		return fmt.Errorf("writeOverlay: marshal: %w", err)
	}
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:270

	err = atomicWriteFile(filepath.Join(cacheDir, "overlay.json"), data, 0o644)
	_ = err // @inco: err == nil, -return(fmt.Errorf("writeOverlay: write: %w", err))
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:272
	if !(err == nil) {
		return fmt.Errorf("writeOverlay: write: %w", err)
	}
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:273

	return nil
}

// loadOverlayIfExists reads the previous overlay.json and returns the
// shadow path map. Returns nil if the file does not exist.
func (e *Engine) loadOverlayIfExists() map[string]string {
	overlayPath := filepath.Join(e.Root, ".inco_cache", "overlay.json")
	data, err := os.ReadFile(overlayPath)
	_ = err // @inco: err == nil, -return(nil)
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:282
	if !(err == nil) {
		return nil
	}
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:283

	var ov Overlay
	err = json.Unmarshal(data, &ov)
	_ = err // @inco: err == nil, -return(nil)
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:286
	if !(err == nil) {
		return nil
	}
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:287

	return ov.Replace
}

// ---------------------------------------------------------------------------
// Manifest I/O (incremental gen)
// ---------------------------------------------------------------------------

func (e *Engine) manifestPath() string {
	return filepath.Join(e.Root, ".inco_cache", "manifest.json")
}

func (e *Engine) loadManifest() *Manifest {
	data, err := os.ReadFile(e.manifestPath())
	_ = err // @inco: err == nil, -return(&Manifest{Files: make(map[string]ManifestEntry)})
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:301
	if !(err == nil) {
		return &Manifest{Files: make(map[string]ManifestEntry)}
	}
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:302

	var m Manifest
	err = json.Unmarshal(data, &m)
	_ = err // @inco: err == nil, -return(&Manifest{Files: make(map[string]ManifestEntry)})
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:305
	if !(err == nil) {
		return &Manifest{Files: make(map[string]ManifestEntry)}
	}
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:306
	if !(m.Files != nil) {
		return &Manifest{Files: make(map[string]ManifestEntry)}
	}
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:307

	return &m
}

func (e *Engine) writeManifest(m *Manifest) error {
	cacheDir := filepath.Join(e.Root, ".inco_cache")
	err := os.MkdirAll(cacheDir, 0o755)
	_ = err // @inco: err == nil, -return(fmt.Errorf("writeManifest: mkdir: %w", err))
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:314
	if !(err == nil) {
		return fmt.Errorf("writeManifest: mkdir: %w", err)
	}
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:315

	data, err := json.MarshalIndent(m, "", "  ")
	_ = err // @inco: err == nil, -return(fmt.Errorf("writeManifest: marshal: %w", err))
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:317
	if !(err == nil) {
		return fmt.Errorf("writeManifest: marshal: %w", err)
	}
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:318

	err = atomicWriteFile(e.manifestPath(), data, 0o644)
	_ = err // @inco: err == nil, -return(fmt.Errorf("writeManifest: write: %w", err))
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:320
	if !(err == nil) {
		return fmt.Errorf("writeManifest: write: %w", err)
	}
//line /home/runner/work/inco/inco/internal/inco/engine.inco.go:321

	return nil
}

// hashBytes returns the hex-encoded SHA-256 of the given content.
func hashBytes(data []byte) string {
	h := sha256.Sum256(data)
	return hex.EncodeToString(h[:])
}
