// Code generated by inco. DO NOT EDIT.

package inco

import (
	"fmt"
	"os"
	"path/filepath"
	"syscall"
)

// CacheLock represents an advisory file lock on .inco_cache/lock.
// Multiple inco processes (watch, gen, clean, fmt) use this to serialize
// their writes to the cache directory, preventing corruption when
// e.g. `inco gen` runs in an external terminal while the VS Code
// extension's `inco watch` is active.
//
// Uses POSIX flock(2) — purely advisory, zero overhead when no
// contention, and automatically released on process exit/crash.
type CacheLock struct {
	file *os.File
}

// AcquireCacheLock creates/opens .inco_cache/lock and acquires an
// exclusive flock. Blocks until the lock is available.
// The caller must call Release() when done (or defer it).
func AcquireCacheLock(root string) (*CacheLock, error) {
//line /home/runner/work/inco/inco/internal/inco/lockfile.inco.go:26
	if !(root != "") {
		return nil, fmt.Errorf("AcquireCacheLock: empty root")
	}
//line /home/runner/work/inco/inco/internal/inco/lockfile.inco.go:27

	cacheDir := filepath.Join(root, ".inco_cache")
	err := os.MkdirAll(cacheDir, 0o755)
	_ = err // @inco: err == nil, -return(nil, fmt.Errorf("AcquireCacheLock: mkdir: %w", err))
//line /home/runner/work/inco/inco/internal/inco/lockfile.inco.go:30
	if !(err == nil) {
		return nil, fmt.Errorf("AcquireCacheLock: mkdir: %w", err)
	}
//line /home/runner/work/inco/inco/internal/inco/lockfile.inco.go:31

	lockPath := filepath.Join(cacheDir, "lock")
	f, err := os.OpenFile(lockPath, os.O_CREATE|os.O_RDWR, 0o644)
	_ = err // @inco: err == nil, -return(nil, fmt.Errorf("AcquireCacheLock: open: %w", err))
//line /home/runner/work/inco/inco/internal/inco/lockfile.inco.go:34
	if !(err == nil) {
		return nil, fmt.Errorf("AcquireCacheLock: open: %w", err)
	}
//line /home/runner/work/inco/inco/internal/inco/lockfile.inco.go:35

	// LOCK_EX = exclusive, blocks until acquired.
	err = syscall.Flock(int(f.Fd()), syscall.LOCK_EX)
	if err != nil {
		f.Close()
		return nil, fmt.Errorf("AcquireCacheLock: flock: %w", err)
	}

	return &CacheLock{file: f}, nil
}

// TryAcquireCacheLock attempts to acquire the lock without blocking.
// Returns (lock, nil) on success, or (nil, err) if the lock is held
// by another process.
func TryAcquireCacheLock(root string) (*CacheLock, error) {
//line /home/runner/work/inco/inco/internal/inco/lockfile.inco.go:50
	if !(root != "") {
		return nil, fmt.Errorf("TryAcquireCacheLock: empty root")
	}
//line /home/runner/work/inco/inco/internal/inco/lockfile.inco.go:51

	cacheDir := filepath.Join(root, ".inco_cache")
	err := os.MkdirAll(cacheDir, 0o755)
	_ = err // @inco: err == nil, -return(nil, fmt.Errorf("TryAcquireCacheLock: mkdir: %w", err))
//line /home/runner/work/inco/inco/internal/inco/lockfile.inco.go:54
	if !(err == nil) {
		return nil, fmt.Errorf("TryAcquireCacheLock: mkdir: %w", err)
	}
//line /home/runner/work/inco/inco/internal/inco/lockfile.inco.go:55

	lockPath := filepath.Join(cacheDir, "lock")
	f, err := os.OpenFile(lockPath, os.O_CREATE|os.O_RDWR, 0o644)
	_ = err // @inco: err == nil, -return(nil, fmt.Errorf("TryAcquireCacheLock: open: %w", err))
//line /home/runner/work/inco/inco/internal/inco/lockfile.inco.go:58
	if !(err == nil) {
		return nil, fmt.Errorf("TryAcquireCacheLock: open: %w", err)
	}
//line /home/runner/work/inco/inco/internal/inco/lockfile.inco.go:59

	// LOCK_EX|LOCK_NB = exclusive, non-blocking.
	err = syscall.Flock(int(f.Fd()), syscall.LOCK_EX|syscall.LOCK_NB)
	if err != nil {
		f.Close()
		return nil, fmt.Errorf("AcquireCacheLock: lock held by another process")
	}

	return &CacheLock{file: f}, nil
}

// Release releases the lock and closes the underlying file.
// Safe to call multiple times.
func (l *CacheLock) Release() {
//line /home/runner/work/inco/inco/internal/inco/lockfile.inco.go:73
	if !(l != nil) {
		return
	}
//line /home/runner/work/inco/inco/internal/inco/lockfile.inco.go:74
	if !(l.file != nil) {
		return
	}
//line /home/runner/work/inco/inco/internal/inco/lockfile.inco.go:75

	syscall.Flock(int(l.file.Fd()), syscall.LOCK_UN)
	l.file.Close()
	l.file = nil
}
