// Code generated by inco. DO NOT EDIT.

//go:build !windows

package inco

import (
	"fmt"
	"os"
	"path/filepath"
	"syscall"
)

// AcquireCacheLock creates/opens .inco_cache/lock and acquires an
// exclusive flock. Blocks until the lock is available.
// The caller must call Release() when done (or defer it).
func AcquireCacheLock(root string) (*CacheLock, error) {
//line /home/runner/work/inco/inco/internal/inco/lockfile_unix.inco.go:16
	if !(root != "") {
		return nil, fmt.Errorf("AcquireCacheLock: empty root")
	}
//line /home/runner/work/inco/inco/internal/inco/lockfile_unix.inco.go:17

	cacheDir := filepath.Join(root, ".inco_cache")
	err := os.MkdirAll(cacheDir, 0o755)
	_ = err // @inco: err == nil, -return(nil, fmt.Errorf("AcquireCacheLock: mkdir: %w", err))
//line /home/runner/work/inco/inco/internal/inco/lockfile_unix.inco.go:20
	if !(err == nil) {
		return nil, fmt.Errorf("AcquireCacheLock: mkdir: %w", err)
	}
//line /home/runner/work/inco/inco/internal/inco/lockfile_unix.inco.go:21

	lockPath := filepath.Join(cacheDir, "lock")
	f, err := os.OpenFile(lockPath, os.O_CREATE|os.O_RDWR, 0o644)
	_ = err // @inco: err == nil, -return(nil, fmt.Errorf("AcquireCacheLock: open: %w", err))
//line /home/runner/work/inco/inco/internal/inco/lockfile_unix.inco.go:24
	if !(err == nil) {
		return nil, fmt.Errorf("AcquireCacheLock: open: %w", err)
	}
//line /home/runner/work/inco/inco/internal/inco/lockfile_unix.inco.go:25

	// LOCK_EX = exclusive, blocks until acquired.
	err = syscall.Flock(int(f.Fd()), syscall.LOCK_EX)
	if err != nil {
		f.Close()
		return nil, fmt.Errorf("AcquireCacheLock: flock: %w", err)
	}

	return &CacheLock{file: f}, nil
}

// TryAcquireCacheLock attempts to acquire the lock without blocking.
// Returns (lock, nil) on success, or (nil, err) if the lock is held
// by another process.
func TryAcquireCacheLock(root string) (*CacheLock, error) {
//line /home/runner/work/inco/inco/internal/inco/lockfile_unix.inco.go:40
	if !(root != "") {
		return nil, fmt.Errorf("TryAcquireCacheLock: empty root")
	}
//line /home/runner/work/inco/inco/internal/inco/lockfile_unix.inco.go:41

	cacheDir := filepath.Join(root, ".inco_cache")
	err := os.MkdirAll(cacheDir, 0o755)
	_ = err // @inco: err == nil, -return(nil, fmt.Errorf("TryAcquireCacheLock: mkdir: %w", err))
//line /home/runner/work/inco/inco/internal/inco/lockfile_unix.inco.go:44
	if !(err == nil) {
		return nil, fmt.Errorf("TryAcquireCacheLock: mkdir: %w", err)
	}
//line /home/runner/work/inco/inco/internal/inco/lockfile_unix.inco.go:45

	lockPath := filepath.Join(cacheDir, "lock")
	f, err := os.OpenFile(lockPath, os.O_CREATE|os.O_RDWR, 0o644)
	_ = err // @inco: err == nil, -return(nil, fmt.Errorf("TryAcquireCacheLock: open: %w", err))
//line /home/runner/work/inco/inco/internal/inco/lockfile_unix.inco.go:48
	if !(err == nil) {
		return nil, fmt.Errorf("TryAcquireCacheLock: open: %w", err)
	}
//line /home/runner/work/inco/inco/internal/inco/lockfile_unix.inco.go:49

	// LOCK_EX|LOCK_NB = exclusive, non-blocking.
	err = syscall.Flock(int(f.Fd()), syscall.LOCK_EX|syscall.LOCK_NB)
	if err != nil {
		f.Close()
		return nil, fmt.Errorf("TryAcquireCacheLock: lock held by another process")
	}

	return &CacheLock{file: f}, nil
}

// Release releases the lock and closes the underlying file.
// Safe to call multiple times.
func (l *CacheLock) Release() {
//line /home/runner/work/inco/inco/internal/inco/lockfile_unix.inco.go:63
	if !(l != nil) {
		return
	}
//line /home/runner/work/inco/inco/internal/inco/lockfile_unix.inco.go:64
	if !(l.file != nil) {
		return
	}
//line /home/runner/work/inco/inco/internal/inco/lockfile_unix.inco.go:65

	syscall.Flock(int(l.file.Fd()), syscall.LOCK_UN)
	l.file.Close()
	l.file = nil
}
