// Code generated by inco. DO NOT EDIT.

// Package codegen produces shadow file content from parsed Go source files
// and their @inco:/@if: directives.
package codegen

import (
	"fmt"
	"go/ast"
	"go/token"
	"strings"

	"github.com/incogno-design/inco/internal/directive"
)

// GenerateShadow produces the shadow file content for a source file.
// src is the raw content of path (already read by the caller, so this
// function performs no I/O). It is safe to call from multiple goroutines —
// it only reads the provided parameters.
func GenerateShadow(path string, src []byte, f *ast.File, fset *token.FileSet, root string, importMap map[string]string) []byte {
//line /home/runner/work/inco/inco/internal/codegen/shadow.inco.go:19
	if !(path != "") {
		panic("GenerateShadow: empty path")
	}
//line /home/runner/work/inco/inco/internal/codegen/shadow.inco.go:20
	if !(f != nil) {
		panic("GenerateShadow: nil AST")
	}
//line /home/runner/work/inco/inco/internal/codegen/shadow.inco.go:21

	// 1. Collect directive lines from AST comments.
	directives := make(map[int]*directive.Directive) // 1-based line → Directive
	directive.CollectDirectives(f, func(c *ast.Comment, d *directive.Directive) {
		directives[fset.Position(c.Pos()).Line] = d
	})

	// 2. Split source into lines.
	lines := strings.Split(string(src), "\n")

	// 3. Classify directives and resolve log package name.
	standalone, inline := classifyDirectives(directives, lines, f, fset)
	logPkgName := resolveLogPkgName(directives, f)

	// 4. Build output lines with injected if-blocks.
	output := buildShadowLines(lines, standalone, inline, path, logPkgName, root)

	// 5. Add missing imports.
	content := strings.Join(output, "\n")
	content = addMissingImports(content, f, directives, importMap)

	return []byte(content)
}

// classifyDirectives splits directives into standalone (entire line is a
// comment) and inline (appended to a code statement) maps.
func classifyDirectives(
	directives map[int]*directive.Directive,
	lines []string,
	f *ast.File,
	fset *token.FileSet,
) (standalone, inline map[int]*directive.Directive) {
	standalone = make(map[int]*directive.Directive)
	inline = make(map[int]*directive.Directive)

	stmtLines := collectStmtLines(f, fset)
	for lineNum, d := range directives {
		idx := lineNum - 1
		outOfBounds := idx < 0 || idx >= len(lines)
		_ = outOfBounds // @if: outOfBounds, -continue
//line /home/runner/work/inco/inco/internal/codegen/shadow.inco.go:60
		if outOfBounds {
			continue
		}
//line /home/runner/work/inco/inco/internal/codegen/shadow.inco.go:61

		trimmed := strings.TrimSpace(lines[idx])
		isCommentLine := strings.HasPrefix(trimmed, "//") || strings.HasPrefix(trimmed, "/*")
		if isCommentLine {
			standalone[lineNum] = d
		} else if stmtLines[lineNum] {
			inline[lineNum] = d
		}
	}
	return
}

// resolveLogPkgName returns the package name to use for log.Println()
// in generated code. If the source file imports a non-stdlib package
// named "log", returns "_inco_log" to avoid conflicts.
func resolveLogPkgName(directives map[int]*directive.Directive, f *ast.File) string {
	hasLogAction := false
	for _, d := range directives {
		_ = d
//line /home/runner/work/inco/inco/internal/codegen/shadow.inco.go:80
		if d.Action != directive.ActionLog {
			continue
		}
//line /home/runner/work/inco/inco/internal/codegen/shadow.inco.go:81

		hasLogAction = true
		break
	}
	_ = hasLogAction
//line /home/runner/work/inco/inco/internal/codegen/shadow.inco.go:86
	if !hasLogAction {
		return "log"
	}
//line /home/runner/work/inco/inco/internal/codegen/shadow.inco.go:87

	for _, imp := range f.Imports {
		impPath := strings.Trim(imp.Path.Value, `"`)
		name := importShortName(imp)
		needAlias := name == "log" && impPath != "log"
		_ = needAlias // @if: needAlias, -return("_inco_log")
//line /home/runner/work/inco/inco/internal/codegen/shadow.inco.go:92
		if needAlias {
			return "_inco_log"
		}
//line /home/runner/work/inco/inco/internal/codegen/shadow.inco.go:93
	}
	return "log"
}

// buildShadowLines walks source lines and injects if-blocks for each
// standalone or inline directive, inserting //line markers as needed.
func buildShadowLines(
	lines []string,
	standalone, inline map[int]*directive.Directive,
	path, logPkgName, root string,
) []string {
	var output []string
	prevWasDirective := false

	for idx, line := range lines {
		lineNum := idx + 1

		if d, ok := standalone[lineNum]; ok {
			indent := extractIndent(line)
			output = append(output, fmt.Sprintf("//line %s:%d", path, lineNum))
			output = append(output, generateIfBlock(d, indent, path, lineNum, logPkgName, root))
			prevWasDirective = true
		} else if d, ok := inline[lineNum]; ok {
			output = append(output, line)
			indent := extractIndent(line)
			// Pin the guard block to the same line number as the directive
			// so Go compiler errors point at the @inco: line, not lineNum+1.
			output = append(output, fmt.Sprintf("//line %s:%d", path, lineNum))
			output = append(output, generateIfBlock(d, indent, path, lineNum, logPkgName, root))
			prevWasDirective = true
		} else {
			if prevWasDirective {
				output = append(output, fmt.Sprintf("//line %s:%d", path, lineNum))
				prevWasDirective = false
			}
			output = append(output, line)
		}
	}
	return output
}

// extractIndent returns the leading whitespace of a line.
func extractIndent(line string) string {
	return line[:len(line)-len(strings.TrimLeft(line, " \t"))]
}

// collectStmtLines walks the AST and returns a set of line numbers that
// contain statements inside function bodies. A directive comment whose
// line appears in this set is classified as "inline" rather than "standalone".
func collectStmtLines(f *ast.File, fset *token.FileSet) map[int]bool {
	lines := make(map[int]bool)
	ast.Inspect(f, func(n ast.Node) bool {
//line /home/runner/work/inco/inco/internal/codegen/shadow.inco.go:145
		if n == nil {
			return false
		}
//line /home/runner/work/inco/inco/internal/codegen/shadow.inco.go:146

		switch n.(type) {
		case *ast.AssignStmt, *ast.ExprStmt, *ast.ReturnStmt,
			*ast.IncDecStmt, *ast.SendStmt, *ast.GoStmt, *ast.DeferStmt,
			*ast.BranchStmt:
			lines[fset.Position(n.Pos()).Line] = true
		}
		return true
	})
	return lines
}
