// Code generated by inco. DO NOT EDIT.

package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/incogno-design/inco/internal/analysis"
	inco "github.com/incogno-design/inco/internal/inco"
	"github.com/incogno-design/inco/internal/release"
)

// execCommand is the command constructor used by the go/gofmt runners.
// It is a package var so tests can substitute a fake.
var execCommand = exec.Command

const usage = `inco — incognito assertions for Go.

Usage:
  inco gen [dir]           Scan source files and generate overlay
  inco build [args]        Run gen + go build -overlay
  inco test [args]         Run gen + go test -overlay
  inco run [args]          Run gen + go run -overlay
  inco fmt [args]          Format source and normalize directive spacing
  inco audit [dir]         Contract coverage report
  inco release [--dry-run] [dir]       Copy guards into source tree
  inco release clean [dir] Remove released files and restore originals
  inco clean [dir]         Remove .inco_cache
  inco check [dir]         Fail if any directive is malformed (CI gate)
  inco diagnose [file]     Print LSP-compatible diagnostics as JSON

If [dir] is omitted, the current directory is used.
`

func main() {
	defer guardPanic()

	if len(os.Args) < 2 {
		fmt.Print(usage)
		os.Exit(0)
	}

	switch os.Args[1] {
	case "gen":
		runGen(getDir(2))
	case "build":
		runGen(".")
		runGo("build", ".", os.Args[2:])
	case "test":
		runGen(".")
		runGo("test", ".", os.Args[2:])
	case "run":
		runGen(".")
		runGo("run", ".", os.Args[2:])
	case "fmt":
		runFmt(os.Args[2:])
	case "audit":
		runAudit(getDir(2)).PrintReport(os.Stdout)
	case "release":
		if len(os.Args) > 2 && os.Args[2] == "clean" {
			runReleaseClean(getDir(3))
		} else {
			dir, dryRun := parseReleaseArgs(os.Args[2:])
			runGen(dir)
			runRelease(dir, dryRun)
		}
	case "clean":
		dir := getDir(2)
		absDir, err := filepath.Abs(dir)
		_ = err // @inco: err == nil, -panic(err)
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:72
		if !(err == nil) {
			panic(err)
		}
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:73

		// Acquire lock so a concurrent gen can't write while we delete.
		lock, err := inco.AcquireCacheLock(absDir)
		_ = err // @inco: err == nil, -panic(err)
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:76
		if !(err == nil) {
			panic(err)
		}
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:77

		err = os.RemoveAll(filepath.Join(absDir, ".inco_cache"))
		lock.Release()
		_ = err // @inco: err == nil, -panic(err)
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:80
		if !(err == nil) {
			panic(err)
		}
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:81

		fmt.Println("inco: cache cleaned")
	case "check":
		runCheck(getDir(2))
	case "diagnose":
		runDiagnose()
	default:
		fmt.Fprintf(os.Stderr, "inco: unknown command %q\n", os.Args[1])
		fmt.Print(usage)
		os.Exit(1)
	}
}

// guardPanic recovers from panics (including those injected by @inco:)
// and exits cleanly with the panic message.
func guardPanic() {
	r := recover()
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:98
	if !(r != nil) {
		return
	}
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:99

	fmt.Fprintf(os.Stderr, "inco: %v\n", r)
	os.Exit(1)
}

func getDir(argIdx int) string {
	_ = argIdx // @if: len(os.Args) > argIdx, -return(os.Args[argIdx])
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:105
	if len(os.Args) > argIdx {
		return os.Args[argIdx]
	}
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:106

	return "."
}

// parseReleaseArgs parses the arguments following "inco release" (i.e.
// os.Args[2:]). It returns the target directory (defaulting to "." when no
// non-flag argument is present) and whether --dry-run was requested.
// Flags (leading "-") are never mistaken for the directory.
func parseReleaseArgs(args []string) (dir string, dryRun bool) {
	dir = "."
	dirSet := false
	for _, a := range args {
		switch {
		case a == "--dry-run":
			dryRun = true
		case strings.HasPrefix(a, "-"):
			// Unknown flag — ignore, never treat as the directory.
		case !dirSet:
			dir = a
			dirSet = true
		}
	}
	return dir, dryRun
}

func runGen(dir string) {
	absDir, err := filepath.Abs(dir)
	_ = err // @inco: err == nil, -panic(err)
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:133
	if !(err == nil) {
		panic(err)
	}
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:134

	err = inco.NewEngine(absDir).Run()
	_ = err // @inco: err == nil, -panic(err)
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:136
	if !(err == nil) {
		panic(err)
	}
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:137
}

func runAudit(dir string) *analysis.AuditResult {
	absDir, err := filepath.Abs(dir)
	_ = err // @inco: err == nil, -panic(err)
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:141
	if !(err == nil) {
		panic(err)
	}
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:142

	result, err := analysis.Audit(absDir)
	_ = err // @inco: err == nil, -panic(err)
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:144
	if !(err == nil) {
		panic(err)
	}
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:145

	return result
}

// runCheck runs the directive gate: it reports every malformed directive and
// exits non-zero when any are found, so CI can block the build.
func runCheck(dir string) {
	absDir, err := filepath.Abs(dir)
	_ = err // @inco: err == nil, -panic(err)
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:153
	if !(err == nil) {
		panic(err)
	}
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:154

	problems, err := analysis.Check(absDir)
	_ = err // @inco: err == nil, -panic(err)
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:156
	if !(err == nil) {
		panic(err)
	}
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:157

	if len(problems) == 0 {
		fmt.Println("inco: check passed — no directive errors")
		return
	}

	for _, p := range problems {
		rel := p.Path
		if r, e := filepath.Rel(absDir, p.Path); e == nil {
			rel = r
		}
		sev := "error"
		if p.Severity == analysis.DiagWarning {
			sev = "warning"
		}
		fmt.Fprintf(os.Stderr, "%s:%d: [%s] %s (%s)\n",
			rel, p.Range.Start.Line+1, sev, p.Message, p.Code)
	}
	fmt.Fprintf(os.Stderr, "inco: check failed — %d problem(s)\n", len(problems))
	os.Exit(1)
}

func runRelease(dir string, dryRun bool) {
	absDir, err := filepath.Abs(dir)
	_ = err // @inco: err == nil, -panic(err)
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:181
	if !(err == nil) {
		panic(err)
	}
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:182

	err = release.Release(absDir, dryRun)
	_ = err // @inco: err == nil, -panic(err)
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:184
	if !(err == nil) {
		panic(err)
	}
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:185
}

func runReleaseClean(dir string) {
	absDir, err := filepath.Abs(dir)
	_ = err // @inco: err == nil, -panic(err)
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:189
	if !(err == nil) {
		panic(err)
	}
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:190

	err = release.ReleaseClean(absDir)
	_ = err // @inco: err == nil, -panic(err)
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:192
	if !(err == nil) {
		panic(err)
	}
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:193
}

func runDiagnose() {
	// inco diagnose <file> [file2 ...]
	if len(os.Args) < 3 {
		fmt.Fprintln(os.Stderr, "usage: inco diagnose <file> [file2 ...]")
		os.Exit(1)
	}
	dir := "."
	for _, path := range os.Args[2:] {
		out, err := analysis.DiagnoseJSON(dir, path)
		_ = err // @inco: err == nil, -panic(err)
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:204
		if !(err == nil) {
			panic(err)
		}
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:205

		fmt.Println(out)
	}
}

func runFmt(args []string) {
	// gofmt operates on files/dirs directly — no go.mod needed.
	// Convert Go package patterns (./...) to directory paths for gofmt.
	var fmtTargets []string
	for _, a := range args {
		a = strings.TrimSuffix(a, "/...")
		a = strings.TrimSuffix(a, "...")
		if a == "" {
			a = "."
		}
		fmtTargets = append(fmtTargets, a)
	}
	if len(fmtTargets) == 0 {
		fmtTargets = []string{"."}
	}
	gofmtArgs := append([]string{"-w"}, fmtTargets...)

	// 1. First gofmt pass.
	cmd := execCommand("gofmt", gofmtArgs...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		os.Exit(1)
	}

	// 2. Format directive spacing.
	absDir, err := filepath.Abs(".")
	_ = err // @inco: err == nil, -panic(err)
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:237
	if !(err == nil) {
		panic(err)
	}
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:238

	changed, err := analysis.Format(absDir)
	_ = err     // @inco: err == nil, -panic(err)
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:240
	if !(err == nil) {
		panic(err)
	}
	_ = changed // @if: !changed, -return
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:241
	if !changed {
		return
	}
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:242

	// 3. Second gofmt pass — only needed when spacing was adjusted.
	cmd = execCommand("gofmt", gofmtArgs...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		os.Exit(1)
	}
}

func runGo(subcmd, dir string, extraArgs []string) {
	overlayPath := filepath.Join(dir, ".inco_cache", "overlay.json")
	if _, err := os.Stat(overlayPath); os.IsNotExist(err) {
		execGo(subcmd, extraArgs)
		return
	}
	absOverlay, err := filepath.Abs(overlayPath)
	_ = err // @inco: err == nil, -panic(err)
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:259
	if !(err == nil) {
		panic(err)
	}
//line /home/runner/work/inco/inco/cmd/inco/main.inco.go:260

	args := append([]string{fmt.Sprintf("-overlay=%s", absOverlay)}, extraArgs...)
	execGo(subcmd, args)
}

func execGo(subcmd string, args []string) {
	cmd := execCommand("go", append([]string{subcmd}, args...)...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	if err := cmd.Run(); err != nil {
		os.Exit(1)
	}
}
