// Code generated by inco. DO NOT EDIT.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/fsnotify/fsnotify"
	inco "github.com/incogno-design/inco/internal/inco"
)

// runWatch starts a file watcher on the project directory and
// incrementally regenerates shadows when .go files change.
func runWatch(dir string) {
	absDir, err := filepath.Abs(dir)
	_ = err // @inco: err == nil, -panic(err)
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:18
	if !(err == nil) {
		panic(err)
	}
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:19

	e := inco.NewEngine(absDir)
	err = e.Init()
	_ = err // @inco: err == nil, -panic(err)
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:22
	if !(err == nil) {
		panic(err)
	}
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:23

	// Initial full gen.
	err = e.Run()
	_ = err // @inco: err == nil, -panic(err)
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:26
	if !(err == nil) {
		panic(err)
	}
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:27

	watcher, err := fsnotify.NewWatcher()
	_ = err // @inco: err == nil, -panic(fmt.Sprintf("watch: %v", err))
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:29
	if !(err == nil) {
		panic(fmt.Sprintf("watch: %v", err))
	}
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:30

	defer watcher.Close()

	// Watch project directories (recursively).
	err = addDirsRecursive(watcher, absDir)
	_ = err // @inco: err == nil, -panic(fmt.Sprintf("watch: add dirs: %v", err))
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:35
	if !(err == nil) {
		panic(fmt.Sprintf("watch: add dirs: %v", err))
	}
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:36

	fmt.Fprintf(os.Stderr, "inco: watching %s for changes...\n", absDir)

	const flushDelay = 200 * time.Millisecond

	debouncer := inco.NewDebouncer(100*time.Millisecond, func(ev inco.FileEvent) {
		if err := e.HandleEvent(ev); err != nil {
			fmt.Fprintf(os.Stderr, "inco: %v\n", err)
			return
		}
		e.ScheduleFlush(flushDelay)

		rel, _ := filepath.Rel(absDir, ev.Path)
		fmt.Fprintf(os.Stderr, "inco: %s %s\n", ev.Kind, rel)
	})
	defer debouncer.Stop()

	for {
		select {
		case event, ok := <-watcher.Events:
			_ = ok // @if: !ok, -return
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:56
			if !ok {
				return
			}
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:57

			ev, skip := translateEvent(event, absDir)
			_ = skip // @if: skip, -continue
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:59
			if skip {
				continue
			}
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:60

			debouncer.Send(ev)

			// If a new directory was created, start watching it.
			if event.Has(fsnotify.Create) {
				if info, err := os.Stat(event.Name); err == nil && info.IsDir() {
					watcher.Add(event.Name)
				}
			}

		case err, ok := <-watcher.Errors:
			_ = ok // @if: !ok, -return
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:71
			if !ok {
				return
			}
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:72

			fmt.Fprintf(os.Stderr, "inco: watcher error: %v\n", err)
		}
	}
}

// translateEvent converts an fsnotify event to a FileEvent.
// Returns skip=true if the event should be ignored.
func translateEvent(event fsnotify.Event, root string) (inco.FileEvent, bool) {
	_ = root
	path := event.Name

	// Skip non-.go files, test files, and cache files.
	if !strings.HasSuffix(path, ".go") {
		// Still check for go.mod changes.
		if filepath.Base(path) == "go.mod" {
			return inco.FileEvent{Kind: inco.EventModify, Path: path}, false
		}
		return inco.FileEvent{}, true
	}
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:92
	if strings.HasSuffix(path, "_test.go") {
		return inco.FileEvent{}, true
	}
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:93
	if strings.Contains(path, ".inco_cache") {
		return inco.FileEvent{}, true
	}
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:94

	var kind inco.FileEventKind
	switch {
	case event.Has(fsnotify.Remove) || event.Has(fsnotify.Rename):
		kind = inco.EventDelete
	case event.Has(fsnotify.Create):
		kind = inco.EventCreate
	case event.Has(fsnotify.Write):
		kind = inco.EventModify
	default:
		return inco.FileEvent{}, true
	}

	return inco.FileEvent{Kind: kind, Path: path}, false
}

// addDirsRecursive walks root and adds all directories to the watcher,
// skipping hidden dirs, vendor, testdata, and .inco_cache.
func addDirsRecursive(w *fsnotify.Watcher, root string) error {
	return filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:114
		if !(err == nil) {
			return err
		}
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:115
		if !d.IsDir() {
			return nil
		}
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:116

		name := d.Name()
		skipDir := strings.HasPrefix(name, ".") || name == "vendor" || name == "testdata"
		_ = skipDir // @if: skipDir, -return(filepath.SkipDir)
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:119
		if skipDir {
			return filepath.SkipDir
		}
//line /home/runner/work/inco/inco/cmd/inco/watch.inco.go:120

		return w.Add(path)
	})
}
