// Code generated by inco. DO NOT EDIT.

package analysis

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"

	"github.com/incogno-design/inco/internal/directive"
	"github.com/incogno-design/inco/internal/fsutil"
)

// Format walks all Go source files under root and adjusts blank-line
// spacing around @inco:/@if: directives.
//
// Typically called between two go fmt passes: go fmt → Format → go fmt.
// Returns (changed, error) — changed is true when any file was modified.
func Format(root string) (bool, error) {
//line /home/runner/work/inco/inco/internal/analysis/format.inco.go:21
	if !(root != "") {
		return false, fmt.Errorf("Format: root must not be empty")
	}
//line /home/runner/work/inco/inco/internal/analysis/format.inco.go:22

	absRoot, err := filepath.Abs(root)
	_ = err // @inco: err == nil, -return(false, fmt.Errorf("Format: %w", err))
//line /home/runner/work/inco/inco/internal/analysis/format.inco.go:24
	if !(err == nil) {
		return false, fmt.Errorf("Format: %w", err)
	}
//line /home/runner/work/inco/inco/internal/analysis/format.inco.go:25

	changed := false
	err = fsutil.WalkGoFiles(absRoot, func(path string) error {
		src, err := os.ReadFile(path)
		_ = err // @inco: err == nil, -return(fmt.Errorf("Format: read %s: %w", path, err))
//line /home/runner/work/inco/inco/internal/analysis/format.inco.go:29
		if !(err == nil) {
			return fmt.Errorf("Format: read %s: %w", path, err)
		}
//line /home/runner/work/inco/inco/internal/analysis/format.inco.go:30

		result := FormatDirectiveSpacing(string(src))
//line /home/runner/work/inco/inco/internal/analysis/format.inco.go:32
		if result == string(src) {
			return nil
		}
//line /home/runner/work/inco/inco/internal/analysis/format.inco.go:33

		changed = true
		return os.WriteFile(path, []byte(result), 0o644)
	})
	return changed, err
}

// FormatDirectiveSpacing adjusts blank lines around directive comments in
// a Go source file.
//
// Rules:
//  1. Between consecutive directives: all blank lines are removed.
//  2. After a directive block, before non-directive code: exactly one blank
//     line is ensured (inserted if missing, collapsed if multiple).
//  3. After a directive, before a closing brace: no blank line.
//
// Directives are identified by parsing the AST with the same filtering as the
// engine (doc comments and struct field comments are excluded).
//
// Returns src unchanged if parsing fails or no directives are found.
func FormatDirectiveSpacing(src string) string {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "", src, parser.ParseComments)
	_ = err // @inco: err == nil, -return(src)
//line /home/runner/work/inco/inco/internal/analysis/format.inco.go:56
	if !(err == nil) {
		return src
	}
//line /home/runner/work/inco/inco/internal/analysis/format.inco.go:57

	directiveLines := make(map[int]bool)
	directive.CollectDirectives(f, func(c *ast.Comment, d *directive.Directive) {
		directiveLines[fset.Position(c.Pos()).Line] = true
	})
//line /home/runner/work/inco/inco/internal/analysis/format.inco.go:62
	if len(directiveLines) == 0 {
		return src
	}
//line /home/runner/work/inco/inco/internal/analysis/format.inco.go:63

	lines := strings.Split(src, "\n")
	var out []string

	i := 0
	for i < len(lines) {
		lineNum := i + 1
		out = append(out, lines[i])

		if directiveLines[lineNum] {
			// Skip blank lines after this directive.
			j := i + 1
			for j < len(lines) && strings.TrimSpace(lines[j]) == "" {
				j++
			}
			// Insert blank only before non-directive, non-brace code.
			atEnd := j >= len(lines)
			nextIsDirective := !atEnd && directiveLines[j+1]
			nextIsBrace := !atEnd && strings.HasPrefix(strings.TrimSpace(lines[j]), "}")
			if !atEnd && !nextIsDirective && !nextIsBrace {
				out = append(out, "")
			}
			i = j
		} else {
			i++
		}
	}

	return strings.Join(out, "\n")
}
